apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: springapp-deployment
spec:
  selector:
    matchLabels:
      app: springapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springapp
        image: springapp:12
        ports:
        - containerPort: 9091