job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/nikolamarasovic/SpringBoot.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'C:/Users/enimara/Downloads/app/app_new/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.war'
    }
}